### PR TITLE
Welcome Actuator

### PR DESCRIPTION
**Pull request by mzottola**

### CODE REVIEW

**Comment by mzottola** [comment]
> I'm not sure I understood what you are doing byt why not using the spring web security standard
configuration https://spring.io/guides/gs/securing-web/ ?

The default implementation described is very simple and is just an example.
What don't you understand ?

**Comment by mzottola** [comment]
[Add actuator to project](https://trello.com/c/Pl1sJMqX/15-add-actuator-to-project)

**Comment by mzottola** [comment]
> It seems to need some configuration to be really usefull but I will do it

I just tested the 'health' endpoint, it works.
What are you talking about ?

**Comment by jeromelebaron** [comment]
> > It seems to need some configuration to be really usefull but I will do it
> 
> I just tested the 'health' endpoint, it works.
> What are you talking about ?

@mzottola I was talking about adding some more informations and configuration to actuator but I created a task for that https://trello.com/c/X4U4MJMq

**Pull request merged**
